---
language: java
install: skip

os: linux
dist: focal
jdk: openjdk11

git:
  quiet: true
  clone: false

jobs:
  include:
    - stage: init
      workspaces:
        create:
          name: base
          paths: .
      script:
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh > install.sh"
        - "sudo bash install.sh -b ."
      git:
        clone: true

    - stage: check
      name: "Detekt"
      workspaces:
        use: base
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew detekt
    - name: "Fossa"
      workspaces:
        use: base
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./fossa analyze --branch "$TRAVIS_BRANCH"

    - stage: compile
      workspaces:
        create:
          name: compiled
          paths: .
        use: base
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew classes

    - stage: test
      name: "Unit tests"
      workspaces:
        use: compiled
        create:
          name: tests
          paths: .
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew test
    - name: "License check"
      workspaces:
        use: compiled
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./fossa test

    - stage: report
      name: "Codecov"
      workspaces:
        use: tests
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash) -B "$TRAVIS_BRANCH"

    - stage: build & publish artifact
      workspaces:
        use: compiled
      script:
        - cd $TRAVIS_BUILD_DIR
        - ./gradlew bootJar publish