---
language: java
install: skip

os: linux
dist: focal
jdk: openjdk11

git:
  quiet: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: init
      workspaces:
        create:
          name: base
          paths: .
      script:
        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh > install.sh"
        - "sudo bash install.sh -b ."
        - "echo $PWD"
        - "echo ls -al"
    - stage: check
      name: "Detekt"
      workspaces:
        use: base
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - "./gradlew detekt"
    - name: "Fossa"
      workspaces:
        use: base
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - fossa analyze --branch "$TRAVIS_BRANCH"

    - stage: compile
      workspaces:
        create:
          name: compiled
          paths: .
        use: base
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - ./gradlew classes

    - stage: test
      name: "Unit tests"
      workspaces:
        use: compiled
        create:
          name: tests
          paths: .
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - ./gradlew test
    - name: "License check"
      workspaces:
        use: compiled
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - fossa test

    - stage: build artifact
      workspaces:
        use: compiled
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - ./gradlew bootJar

    - stage: report
      name: "Codecov"
      workspaces:
        use: tests
      git:
        clone: false
      script:
        - "cd mathze/gh-playground"
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash) -B "$TRAVIS_BRANCH"