---
language: java
install: skip

os: linux
dist: focal
jdk: openjdk11

git:
  quiet: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

jobs:
  include:
    - stage: check
      name: "Detekt"
      script: ./gradlew detekt
    - name: "Fossa"
      script:
      - fossa analyze --branch "$TRAVIS_BRANCH"

    - stage: compile
      workspaces:
        create:
          name: compiled
          paths:
            - .
      script: ./gradlew classes

    - stage: test
      name: "Unit tests"
      workspaces:
        use:
          compiled
        create:
          name: tests
          paths:
            - .
      script: ./gradlew test
    - name: "License check"
      script: fossa test

    - stage: build artifact
      workspaces:
        use: compiled
      script: ./gradlew bootJar

    - stage: report
      name: "Codecov"
      workspaces:
        use: tests
      script:
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash) -B "$TRAVIS_BRANCH"