name: "Build the project"

on:
  push:
    branches:
      - main
      - develop

jobs:
  init:
    name: "Init"
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-sources-${{ github.run_id }}
      - name: "get fossa"
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh > install.sh
          sudo bash install.sh -b .

  staticChecks:
    name: "Static checks"
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: "Load sources"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-sources-${{ github.run_id }}
      - name: "Load build dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: "Detekt"
        run: ${{ github.workspace }}/gradlew detekt
      - name: "Fossa analyze"
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: ${{ github.workspace }}/fossa analyze --branch ${{ needs.init.outputs.branch }}

  compile:
    runs-on: ubuntu-latest
    needs: staticChecks
    steps:
      - name: "Load sources"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-sources-${{ github.run_id }}
      - name: "Load build dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-compile-${{ github.run_id }}
      - name: "Compile"
        run: ${{ github.workspace }}/gradlew classes

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Load compile cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-compile-${{ github.run_id }}
      - name: "Load build dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-test-${{ github.run_id }}
      - name: "Unit test"
        run: ${{ github.workspace }}/gradlew test

  licenceCheck:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Load sources"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-sources-${{ github.run_id }}
      - name: "Fossa check license"
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: ${{ github.workspace }}/fossa test

  report:
    runs-on: ubuntu-latest
    needs:
      - init
      - test
    steps:
      - name: "Load test cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-test-${{ github.run_id }}
      - name: "Load build dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: "Generate Report"
        run: |
          ${{ github.workspace }}/gradlew jacocoTestReport
          bash <(curl -s https://codecov.io/bash) -B ${{ needs.init.outputs.branch }}

  publish:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: "Load compile cache"
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/**
          key: ${{ runner.os }}-compile-${{ github.run_id }}
      - name: "Load build dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists/**
            ~/.gradle/caches/modules-2/**
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: "Publish"
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
        run: ${{ github.workspace }}/gradlew bootJar publish