on:
  workflow_dispatch:
    inputs:
      source_run_id:
        required: false
        description: "run id of the workflow to which to attach the results"
        default: ""

name: A test workflow

jobs:
  prepareInputs:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.getRunId.outputs.run_id }}
    steps:
      - name: Get Run-ID
        id: getRunId
        run: |
          if "${{ github.event.inputs.source_run_id }}" == ""; then
            echo "::set-output name=run_id::${{ github.run_id }}"
          else
            echo "::set-output name=run_id::${{ github.event.inputs.source_run_id }}"
          fi

  runTests:
    name: Run the tests
    runs-on: ubuntu-latest
    needs: prepareInputs
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Unit-Test-Results
          path: build/test-results/**/*.xml

  report:
    runs-on: ubuntu-latest
    needs: runTests
    if: success() || failure()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: Unit-Test-Results
          path: build/test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: always()
        with:
          files: build/test-results/**/*.xml
